CRITICAL - 2022-05-09 14:54:44 --> syntax error, unexpected '<<' (T_SL)
#0 C:\Users\Adasi\Documents\Project_food\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute()
#1 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle()
#2 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt()
#3 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#4 C:\Users\Adasi\Documents\Project_food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\Users\Adasi\Documents\Project_food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\Adasi\\...')
#6 {main}
CRITICAL - 2022-05-09 14:55:13 --> syntax error, unexpected '<<' (T_SL)
#0 C:\Users\Adasi\Documents\Project_food\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute()
#1 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle()
#2 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt()
#3 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#4 C:\Users\Adasi\Documents\Project_food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\Users\Adasi\Documents\Project_food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\Adasi\\...')
#6 {main}
CRITICAL - 2022-05-09 14:55:39 --> syntax error, unexpected '<<' (T_SL)
#0 C:\Users\Adasi\Documents\Project_food\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute()
#1 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle()
#2 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt()
#3 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#4 C:\Users\Adasi\Documents\Project_food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\Users\Adasi\Documents\Project_food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\Adasi\\...')
#6 {main}
CRITICAL - 2022-05-09 14:55:48 --> syntax error, unexpected '<<' (T_SL)
#0 C:\Users\Adasi\Documents\Project_food\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute()
#1 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle()
#2 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt()
#3 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#4 C:\Users\Adasi\Documents\Project_food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\Users\Adasi\Documents\Project_food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\Adasi\\...')
#6 {main}
CRITICAL - 2022-05-09 14:56:51 --> syntax error, unexpected '<<' (T_SL)
#0 C:\Users\Adasi\Documents\Project_food\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute()
#1 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle()
#2 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt()
#3 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#4 C:\Users\Adasi\Documents\Project_food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\Users\Adasi\Documents\Project_food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\Adasi\\...')
#6 {main}
CRITICAL - 2022-05-09 14:56:55 --> syntax error, unexpected '<<' (T_SL)
#0 C:\Users\Adasi\Documents\Project_food\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute()
#1 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle()
#2 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt()
#3 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#4 C:\Users\Adasi\Documents\Project_food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\Users\Adasi\Documents\Project_food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\Adasi\\...')
#6 {main}
CRITICAL - 2022-05-09 14:56:59 --> syntax error, unexpected '<<' (T_SL)
#0 C:\Users\Adasi\Documents\Project_food\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute()
#1 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle()
#2 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt()
#3 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#4 C:\Users\Adasi\Documents\Project_food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\Users\Adasi\Documents\Project_food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\Adasi\\...')
#6 {main}
CRITICAL - 2022-05-09 14:58:35 --> syntax error, unexpected '<<' (T_SL)
#0 C:\Users\Adasi\Documents\Project_food\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute()
#1 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle()
#2 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt()
#3 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#4 C:\Users\Adasi\Documents\Project_food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\Users\Adasi\Documents\Project_food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\Adasi\\...')
#6 {main}
CRITICAL - 2022-05-09 15:00:18 --> syntax error, unexpected '<<' (T_SL)
#0 C:\Users\Adasi\Documents\Project_food\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute()
#1 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle()
#2 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt()
#3 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#4 C:\Users\Adasi\Documents\Project_food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\Users\Adasi\Documents\Project_food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\Adasi\\...')
#6 {main}
CRITICAL - 2022-05-09 15:01:48 --> syntax error, unexpected '<<' (T_SL)
#0 C:\Users\Adasi\Documents\Project_food\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute()
#1 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle()
#2 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt()
#3 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#4 C:\Users\Adasi\Documents\Project_food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\Users\Adasi\Documents\Project_food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\Adasi\\...')
#6 {main}
CRITICAL - 2022-05-09 15:02:52 --> syntax error, unexpected '<<' (T_SL)
#0 C:\Users\Adasi\Documents\Project_food\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute()
#1 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle()
#2 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt()
#3 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#4 C:\Users\Adasi\Documents\Project_food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\Users\Adasi\Documents\Project_food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\Adasi\\...')
#6 {main}
CRITICAL - 2022-05-09 15:03:08 --> syntax error, unexpected '<<' (T_SL)
#0 C:\Users\Adasi\Documents\Project_food\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute()
#1 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle()
#2 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt()
#3 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#4 C:\Users\Adasi\Documents\Project_food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\Users\Adasi\Documents\Project_food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\Adasi\\...')
#6 {main}
CRITICAL - 2022-05-09 15:03:40 --> syntax error, unexpected '<<' (T_SL)
#0 C:\Users\Adasi\Documents\Project_food\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute()
#1 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle()
#2 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt()
#3 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#4 C:\Users\Adasi\Documents\Project_food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\Users\Adasi\Documents\Project_food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\Adasi\\...')
#6 {main}
CRITICAL - 2022-05-09 15:03:47 --> syntax error, unexpected '<<' (T_SL)
#0 C:\Users\Adasi\Documents\Project_food\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute()
#1 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle()
#2 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt()
#3 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#4 C:\Users\Adasi\Documents\Project_food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\Users\Adasi\Documents\Project_food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\Adasi\\...')
#6 {main}
CRITICAL - 2022-05-09 15:03:58 --> syntax error, unexpected '<<' (T_SL)
#0 C:\Users\Adasi\Documents\Project_food\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute()
#1 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle()
#2 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt()
#3 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#4 C:\Users\Adasi\Documents\Project_food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\Users\Adasi\Documents\Project_food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\Adasi\\...')
#6 {main}
CRITICAL - 2022-05-09 15:04:03 --> syntax error, unexpected '<<' (T_SL)
#0 C:\Users\Adasi\Documents\Project_food\system\Router\Router.php(175): CodeIgniter\Router\Router->autoRoute()
#1 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(719): CodeIgniter\Router\Router->handle()
#2 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->tryToRouteIt()
#3 C:\Users\Adasi\Documents\Project_food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#4 C:\Users\Adasi\Documents\Project_food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#5 C:\Users\Adasi\Documents\Project_food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\Adasi\\...')
#6 {main}
ERROR - 2022-05-09 20:05:44 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;. in C:\Users\bets1\Food\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
CRITICAL - 2022-05-09 20:05:44 --> pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
ERROR - 2022-05-09 20:14:46 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;. in C:\Users\bets1\Food\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
CRITICAL - 2022-05-09 20:14:46 --> pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
ERROR - 2022-05-09 20:19:22 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;. in C:\Users\bets1\Food\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
CRITICAL - 2022-05-09 20:19:22 --> pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
ERROR - 2022-05-09 20:19:26 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;. in C:\Users\bets1\Food\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
CRITICAL - 2022-05-09 20:19:26 --> pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
ERROR - 2022-05-09 20:20:07 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;. in C:\Users\bets1\Food\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
CRITICAL - 2022-05-09 20:20:07 --> pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
ERROR - 2022-05-09 20:22:44 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;. in C:\Users\bets1\Food\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
CRITICAL - 2022-05-09 20:22:44 --> pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
ERROR - 2022-05-09 20:23:21 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;. in C:\Users\bets1\Food\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
CRITICAL - 2022-05-09 20:23:21 --> pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
ERROR - 2022-05-09 20:23:26 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '10'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;. in C:\Users\bets1\Food\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
CRITICAL - 2022-05-09 20:23:26 --> pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '10'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
ERROR - 2022-05-09 20:23:29 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;. in C:\Users\bets1\Food\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
CRITICAL - 2022-05-09 20:23:29 --> pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
ERROR - 2022-05-09 20:23:32 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;. in C:\Users\bets1\Food\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
CRITICAL - 2022-05-09 20:23:32 --> pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
ERROR - 2022-05-09 20:23:55 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '10'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;. in C:\Users\bets1\Food\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
CRITICAL - 2022-05-09 20:23:55 --> pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '10'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
ERROR - 2022-05-09 20:24:03 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;. in C:\Users\bets1\Food\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
CRITICAL - 2022-05-09 20:24:03 --> pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
ERROR - 2022-05-09 20:25:57 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;. in C:\Users\bets1\Food\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
CRITICAL - 2022-05-09 20:25:57 --> pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
ERROR - 2022-05-09 20:27:17 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;. in C:\Users\bets1\Food\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
CRITICAL - 2022-05-09 20:27:17 --> pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
ERROR - 2022-05-09 20:29:56 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '10'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;. in C:\Users\bets1\Food\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
CRITICAL - 2022-05-09 20:29:56 --> pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '10'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
ERROR - 2022-05-09 20:30:26 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '10'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;. in C:\Users\bets1\Food\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
CRITICAL - 2022-05-09 20:30:26 --> pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '10'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
ERROR - 2022-05-09 20:30:29 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;. in C:\Users\bets1\Food\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
CRITICAL - 2022-05-09 20:30:29 --> pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
CRITICAL - 2022-05-09 20:31:47 --> finfo::file(C:\Users\bets1\Food\writable\uploads/produtos/'   data.imagemPrimeiroProduto   '): failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\app\Controllers\Produto.php(114): finfo->file()
#2 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->imagem()
#3 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#4 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#5 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#7 {main}
CRITICAL - 2022-05-09 20:31:48 --> finfo::file(C:\Users\bets1\Food\writable\uploads/produtos/'   data.imagemSegundoProduto   '): failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\app\Controllers\Produto.php(114): finfo->file()
#2 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->imagem()
#3 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#4 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#5 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#7 {main}
CRITICAL - 2022-05-09 20:31:57 --> finfo::file(C:\Users\bets1\Food\writable\uploads/produtos/'   data.imagemPrimeiroProduto   '): failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\app\Controllers\Produto.php(114): finfo->file()
#2 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->imagem()
#3 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#4 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#5 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#7 {main}
CRITICAL - 2022-05-09 20:31:57 --> finfo::file(C:\Users\bets1\Food\writable\uploads/produtos/'   data.imagemSegundoProduto   '): failed to open stream: No such file or directory
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\app\Controllers\Produto.php(114): finfo->file()
#2 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->imagem()
#3 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#4 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#5 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#6 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#7 {main}
ERROR - 2022-05-09 20:32:27 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '10'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;. in C:\Users\bets1\Food\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
CRITICAL - 2022-05-09 20:32:27 --> pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '10'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
ERROR - 2022-05-09 20:33:13 --> ErrorException: pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;. in C:\Users\bets1\Food\system\Database\Postgre\Connection.php:135
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
CRITICAL - 2022-05-09 20:33:13 --> pg_query(): Query failed: ERROR:  column &quot;ide&quot; does not exist
LINE 3: WHERE &quot;ide&quot; = '9'
              ^
HINT:  Perhaps you meant to reference the column &quot;produtos.id&quot;.
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
#1 C:\Users\bets1\Food\system\Database\Postgre\Connection.php(135): pg_query()
#2 C:\Users\bets1\Food\system\Database\BaseConnection.php(670): CodeIgniter\Database\Postgre\Connection->execute()
#3 C:\Users\bets1\Food\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery()
#4 C:\Users\bets1\Food\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query()
#5 C:\Users\bets1\Food\system\Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#6 C:\Users\bets1\Food\system\BaseModel.php(622): CodeIgniter\Model->doFirst()
#7 C:\Users\bets1\Food\app\Controllers\Produto.php(83): CodeIgniter\BaseModel->first()
#8 C:\Users\bets1\Food\system\CodeIgniter.php(825): App\Controllers\Produto->procurar()
#9 C:\Users\bets1\Food\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController()
#10 C:\Users\bets1\Food\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest()
#11 C:\Users\bets1\Food\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 C:\Users\bets1\Food\system\Commands\Server\rewrite.php(43): require_once('C:\\Users\\bets1\\...')
#13 {main}
